### ISSUE TITLE
cant create a liquidity pool with my token

### ISSUE THREAD

**Issue by bob9090** [mimoprotocol/bugtracker#11]
hello i have created a xrc20 token but I can’t make a liquidity pool with it can you help me please ?

**Comment by PietroMaxi** [comment]
Thanks for reporting! we will look into this.

**Comment by PietroMaxi** [comment]
It should have been fixed.

**Comment by bob9090** [comment]
Yes it’s perfect how can I list my token on mimo ?

Envoyé de mon iPhone
